### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'protocol' of 'window.location' as it is undefined.

### ISSUE THREAD

**Issue by SaberDoTcodeR** [oxydev/SubsCrypt-front#10]
This problem is occurring in some situations, but I can not reproduce it. It is reported [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/subscrypt_2_Noc2.md).

**Comment by SaberDoTcodeR** [comment]
https://github.com/w3f/Grant-Milestone-Delivery/pull/250

**Comment by mmagician** [comment]
@SaberDoTcodeR I am getting the same error. Steps:
1. Clone [the repo](https://github.com/oxydev/SubsCrypt-front) & `cd`
2. `yarn install`
3. `yarn run dev`
4. Open `localhost:5000` in the browser
5. Check the terminal again, that's when error happens (same msg as reported in this issue)

**Comment by SaberDoTcodeR** [comment]
@mmagician Can you switch to [this branch ](https://github.com/oxydev/SubsCrypt-front/tree/unhandled-promise-rejection) and run dev again(the trace warning is active right now) and send me the error detail. I was not able to reproduce it.

**Comment by mmagician** [comment]
Sure I did, but I don't think the error is not any more informative than what you already know, hence I didn't include it. Here though:
```
/Users/marcin/dev/SubsCrypt-front/node_modules/next/dist/shared/lib/utils.js:27
    const { protocol , hostname , port  } = window.location;
            ^

TypeError: Cannot destructure property 'protocol' of 'window.location' as it is undefined.
    at Object.getLocationOrigin (/Users/marcin/dev/SubsCrypt-front/node_modules/next/dist/shared/lib/utils.js:27:13)
    at Object.parseRelativeUrl (/Users/marcin/dev/SubsCrypt-front/node_modules/next/dist/shared/lib/router/utils/parse-relative-url.js:9:89)
    at Object.parseUrl (/Users/marcin/dev/SubsCrypt-front/node_modules/next/dist/shared/lib/router/utils/parse-url.js:10:39)
    at Object.parseNextUrl (/Users/marcin/dev/SubsCrypt-front/node_modules/next/dist/shared/lib/router/utils/parse-next-url.js:10:38)
    at DevServer.handleRequest (/Users/marcin/dev/SubsCrypt-front/node_modules/next/dist/server/next-server.js:189:40)
    at Server.<anonymous> (/Users/marcin/dev/SubsCrypt-front/node_modules/next/dist/server/next.js:54:20)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
error Command failed with exit code 1.
```

**Comment by SaberDoTcodeR** [comment]
Thank, can you indicate your npm and node version?

**Comment by mmagician** [comment]
```
➜  ~ npm --version
7.20.3
➜  ~ node --version
v15.11.0
```

**Comment by SaberDoTcodeR** [comment]
@mmagician problem is solved now. In some versions of node when we used the SubsCrypt npm package the window variable was undefined. It is now dynamically import and working fine. Please check the branch and if it's fine I can merge the pull request.

**Comment by mmagician** [comment]
That fixed it 👍🏼
